module MasterySkill exposing (..)

import CustomTypes exposing (..)


initMasterySkills : List MasterySkill
initMasterySkills =
    [ MasterySkill 0 "HP +5" [ 0, 1 ]
    , MasterySkill 1 "Speed +2" [ 2 ]
    , MasterySkill 2 "Defense +2" [ 3 ]
    , MasterySkill 3 "Strength +2" [ 4 ]
    , MasterySkill 4 "Magic +2" [ 5 ]
    , MasterySkill 4 "Magic +2" [ 5 ]
    , MasterySkill 4 "Magic +2" [ 5 ]
    , MasterySkill 4 "Magic +2" [ 5 ]
    , MasterySkill 4 "Magic +2" [ 5 ]
    , MasterySkill 4 "Magic +2" [ 5 ]
    , MasterySkill 4 "Magic +2" [ 5 ]
    , MasterySkill 4 "Magic +2" [ 5 ]
    , MasterySkill 4 "Magic +2" [ 5 ]
    , MasterySkill 4 "Magic +2" [ 5 ]
    , MasterySkill 4 "Magic +2" [ 5 ]
    , MasterySkill 4 "Magic +2" [ 5 ]
    , MasterySkill 4 "Magic +2" [ 5 ]
    , MasterySkill 4 "Magic +2" [ 5 ]
    , MasterySkill 4 "Magic +2" [ 5 ]
    , MasterySkill 4 "Magic +2" [ 5 ]
    , MasterySkill 4 "Magic +2" [ 5 ]
    , MasterySkill 4 "Magic +2" [ 5 ]
    , MasterySkill 4 "Magic +2" [ 5 ]
    , MasterySkill 4 "Magic +2" [ 5 ]
    , MasterySkill 4 "Magic +2" [ 5 ]
    , MasterySkill 4 "Magic +2" [ 5 ]
    , MasterySkill 4 "Magic +2" [ 5 ]
    , MasterySkill 4 "Magic +2" [ 5 ]
    , MasterySkill 4 "Magic +2" [ 5 ]
    , MasterySkill 4 "Magic +2" [ 5 ]
    , MasterySkill 4 "Magic +2" [ 5 ]
    , MasterySkill 4 "Magic +2" [ 5 ]
    , MasterySkill 4 "Magic +2" [ 5 ]
    , MasterySkill 4 "Magic +2" [ 5 ]
    , MasterySkill 4 "Magic +2" [ 5 ]
    , MasterySkill 4 "Magic +2" [ 5 ]
    , MasterySkill 4 "Magic +2" [ 5 ]
    , MasterySkill 4 "Magic +2" [ 5 ]
    , MasterySkill 4 "Magic +2" [ 5 ]
    , MasterySkill 4 "Magic +2" [ 5 ]
    , MasterySkill 4 "Magic +2" [ 5 ]
    ]
